### ISSUE TITLE
turn on keep singleton nodes option to subtree()

### ISSUE THREAD

**Issue by guidorice** [ncgr/tripal_phylogeny#13]
Also add UI checkbox for user to toggle these singleton nodes on and off by css styling. (off by default because it does add a lot more visual info to parse).

**Comment by adf-ncgr** [comment]
@guidorice : I'm not seeing the UI toggle for this on lis-stage. possibly I'm blind, and it's not a very major point, was just curious since the commit log seems to suggest you did implement it.

**Comment by guidorice** [comment]
Hmm, it should be there, if you focus on a subtree. The singleton nodes are the grey dots which are smaller then the root node. Please reopen this issue if you have any troubles with this.

![phylotree](https://cloud.githubusercontent.com/assets/766758/20107446/cb73ab56-a595-11e6-938c-cbbc57fe3664.png)

**Comment by adf-ncgr** [comment]
I see the disconnect; I was looking at a subsetted tree generated by taxa selection, which does not present the same option/styling, though it seems like it should?

![image](https://cloud.githubusercontent.com/assets/2009605/20108811/9c273566-a59a-11e6-88c4-ef0406f29cd2.png)

**Comment by guidorice** [comment]
That is a bug, reopening issue.

**Comment by guidorice** [comment]
Fixed and released to prod.
