### ISSUE TITLE
problem with removing taxa filter after focusing on subtree

### ISSUE THREAD

**Issue by guidorice** [ncgr/tripal_phylogeny#14]
adf found this- not sure if it is a bug or feature, will need to trace through the code. To reproduce:

* filter by taxon
* focus on a subtree
* click reset taxa selection in the taxon dialog -- nothing happens

**Comment by guidorice** [comment]
@adf-ncgr I did some testing and thought about this for a while. It does seem like a bug for the user, but it is because of how crossfilter is implemented in this web app. I do not have any good solutions, that I can think of. That is why I changed this from bug to wontfix (at least for now).
1. When you filter by taxa, the crossfilter is updated, the tree component gets all the features matching those taxa and then creates a subtree from that and displays it.
2. Then when you focus on a subtree, the tree component creates that subtree and displays from there. It also updates the crossfilter to say 'hey, filter out everything except this list of feature names'. 
3. Now the known 'universe' of crossfilter consists of just those features. That is why changing the taxa filter does not have any effect in the final step.

**Comment by adf-ncgr** [comment]
makes sense- maybe the thing to do for now to avoid perception of bugginess would be to simply make the taxa dialog aware that no resetting of the taxa selection is possible after a subtree operation has been invoked? ie if I have taxa-filtered, then I request a subtree, I should not be able to click the "reset taxa selection" button until I have actually done any taxa-filtering on the subtree (or until I have reset the phylogram chart). Basically, when the "universe" has changed, the state of that should change too. If that's easy to implement, I'd say it's worth doing, but definitely not a major problem.
